// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorfApp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MorfApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505161547_AddSuppliersAndInventory")]
    partial class AddSuppliersAndInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MorfApp.Domain.Entities.AdminUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsSuperadmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_superadmin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_tenant_id_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.BusinessHour", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ClosesAt")
                        .HasColumnType("text")
                        .HasColumnName("closes_at");

                    b.Property<string>("ClosesAt2")
                        .HasColumnType("text")
                        .HasColumnName("closes_at2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<string>("OpensAt")
                        .HasColumnType("text")
                        .HasColumnName("opens_at");

                    b.Property<string>("OpensAt2")
                        .HasColumnType("text")
                        .HasColumnName("opens_at2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_business_hours");

                    b.HasIndex("TenantId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_business_hours_tenant_id_day_of_week");

                    b.ToTable("business_hours", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AvailableFrom")
                        .HasColumnType("text")
                        .HasColumnName("available_from");

                    b.Property<string>("AvailableTo")
                        .HasColumnType("text")
                        .HasColumnName("available_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_categories_tenant_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.DeliveryConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("DeliveryCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("delivery_cost");

                    b.Property<string>("EstimatedMinutes")
                        .HasColumnType("text")
                        .HasColumnName("estimated_minutes");

                    b.Property<decimal?>("FreeDeliveryFrom")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("free_delivery_from");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_order_amount");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("PickupAddress")
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_configs");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_configs_tenant_id");

                    b.ToTable("delivery_configs", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity_change");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("SupplyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supply_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.ModifierGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int?>("MaxSelect")
                        .HasColumnType("integer")
                        .HasColumnName("max_select");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_modifier_groups");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_modifier_groups_tenant_id");

                    b.ToTable("modifier_groups", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.ModifierOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<decimal>("ExtraPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("extra_price");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_modifier_options");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_modifier_options_group_id");

                    b.ToTable("modifier_options", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("delivery")
                        .HasColumnName("delivery_mode");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ConfirmedAt")
                        .HasDatabaseName("ix_orders_confirmed_at");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_orders_tenant_id_created_at");

                    b.HasIndex("TenantId", "Status", "ConfirmedAt")
                        .HasDatabaseName("ix_orders_tenant_id_status_confirmed_at");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_tenant_id_status_created_at");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.PageView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<string>("ProductId")
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_page_views");

                    b.HasIndex("TenantId", "Event", "CreatedAt")
                        .HasDatabaseName("ix_page_views_tenant_id_event_created_at");

                    b.ToTable("page_views", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.PaymentConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("DeliveryCard")
                        .HasColumnType("boolean")
                        .HasColumnName("delivery_card");

                    b.Property<bool>("DeliveryCash")
                        .HasColumnType("boolean")
                        .HasColumnName("delivery_cash");

                    b.Property<bool>("DeliveryTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("delivery_transfer");

                    b.Property<bool>("PickupCard")
                        .HasColumnType("boolean")
                        .HasColumnName("pickup_card");

                    b.Property<bool>("PickupCash")
                        .HasColumnType("boolean")
                        .HasColumnName("pickup_cash");

                    b.Property<bool>("PickupTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("pickup_transfer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_configs");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_configs_tenant_id");

                    b.ToTable("payment_configs", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBuilder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.ProductSupply", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsUnknownQuantity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unknown_quantity");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity_required");

                    b.Property<string>("SupplyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supply_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_product_supplies");

                    b.ToTable("product_supplies", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.PromoRedemption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PromotionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promotion_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_promo_redemptions");

                    b.HasIndex("PromotionId", "PhoneNumber")
                        .HasDatabaseName("ix_promo_redemptions_promotion_id_phone_number");

                    b.HasIndex("TenantId", "PhoneNumber")
                        .HasDatabaseName("ix_promo_redemptions_tenant_id_phone_number");

                    b.ToTable("promo_redemptions", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxPerUser")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("product_ids");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_promotions_tenant_id");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_refresh_tokens_admin_user_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.SetupToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_setup_tokens");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_setup_tokens_admin_user_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_setup_tokens_token");

                    b.ToTable("setup_tokens", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.SuperAdminSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("NotificationMessageTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_message_template");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_super_admin_settings");

                    b.ToTable("super_admin_settings", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Supply", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_stock");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SupplierId")
                        .HasColumnType("text")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_supplies");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.SupplyPurchase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_per_unit");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("QuantityPurchased")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity_purchased");

                    b.Property<string>("SupplierId")
                        .HasColumnType("text")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supply_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("pk_supply_purchases");

                    b.ToTable("supply_purchases", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text")
                        .HasColumnName("custom_domain");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("text")
                        .HasColumnName("owner_email");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubscriptionEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_ends_at");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatsAppMessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("whats_app_message_template");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_number");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_custom_domain");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.TenantBranding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text")
                        .HasColumnName("banner_url");

                    b.Property<string>("ColorAccent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_accent");

                    b.Property<string>("ColorPrimary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_primary");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmojiIcon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji_icon");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_brandings");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_brandings_tenant_id");

                    b.ToTable("tenant_brandings", (string)null);
                });

            modelBuilder.Entity("product_modifier_groups", b =>
                {
                    b.Property<string>("product_id")
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("modifier_group_id")
                        .HasColumnType("text")
                        .HasColumnName("modifier_group_id");

                    b.HasKey("product_id", "modifier_group_id")
                        .HasName("pk_product_modifier_groups");

                    b.HasIndex("modifier_group_id")
                        .HasDatabaseName("ix_product_modifier_groups_modifier_group_id");

                    b.ToTable("product_modifier_groups", (string)null);
                });

            modelBuilder.Entity("promotion_modifier_groups", b =>
                {
                    b.Property<string>("promotion_id")
                        .HasColumnType("text")
                        .HasColumnName("promotion_id");

                    b.Property<string>("modifier_group_id")
                        .HasColumnType("text")
                        .HasColumnName("modifier_group_id");

                    b.HasKey("promotion_id", "modifier_group_id")
                        .HasName("pk_promotion_modifier_groups");

                    b.HasIndex("modifier_group_id")
                        .HasDatabaseName("ix_promotion_modifier_groups_modifier_group_id");

                    b.ToTable("promotion_modifier_groups", (string)null);
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AdminUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_admin_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.BusinessHour", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("BusinessHours")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_hours_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Categories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.DeliveryConfig", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithOne("DeliveryConfig")
                        .HasForeignKey("MorfApp.Domain.Entities.DeliveryConfig", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_configs_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.ModifierGroup", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ModifierGroups")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modifier_groups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.ModifierOption", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.ModifierGroup", "Group")
                        .WithMany("Options")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modifier_options_modifier_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Order", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Orders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.PageView", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("PageViews")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_views_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.PaymentConfig", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithOne("PaymentConfig")
                        .HasForeignKey("MorfApp.Domain.Entities.PaymentConfig", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_configs_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Product", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_tenants_tenant_id");

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.PromoRedemption", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Promotion", "Promotion")
                        .WithMany("Redemptions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_redemptions_promotions_promotion_id");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Promotion", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Promotions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotions_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.SetupToken", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_setup_tokens_admin_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.TenantBranding", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Branding")
                        .HasForeignKey("MorfApp.Domain.Entities.TenantBranding", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_brandings_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("product_modifier_groups", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.ModifierGroup", null)
                        .WithMany()
                        .HasForeignKey("modifier_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_modifier_groups_modifier_groups_modifier_group_id");

                    b.HasOne("MorfApp.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_modifier_groups_products_product_id");
                });

            modelBuilder.Entity("promotion_modifier_groups", b =>
                {
                    b.HasOne("MorfApp.Domain.Entities.ModifierGroup", null)
                        .WithMany()
                        .HasForeignKey("modifier_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_modifier_groups_modifier_groups_modifier_group_id");

                    b.HasOne("MorfApp.Domain.Entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("promotion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_modifier_groups_promotions_promotion_id");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.ModifierGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("MorfApp.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AdminUsers");

                    b.Navigation("Branding");

                    b.Navigation("BusinessHours");

                    b.Navigation("Categories");

                    b.Navigation("DeliveryConfig");

                    b.Navigation("ModifierGroups");

                    b.Navigation("Orders");

                    b.Navigation("PageViews");

                    b.Navigation("PaymentConfig");

                    b.Navigation("Products");

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
